name: Database CI

on:
  push:
  pull_request:

jobs:
  database:
    name: Database
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Verify database port
        run: |
          for i in {1..30}; do
            if (echo > /dev/tcp/localhost/5432) >/dev/null 2>&1; then
              echo "Database is up"
              exit 0
            fi
            sleep 2
          done
          echo "Database failed to start"
          exit 1
